server:
    port: 8443
    ssl:
        enabled: true
        # web_practice 디렉토리 기준
        key-store: backend/spring_security/src/main/resources/spring_security.p12
        key-store-password: spring_security
        key-store-type: PKCS12
        key-alias: spring_security

spring:
    security:
        user:
            name: root
            password: rootroot
