server:
    port: 8443
    ssl:
        enabled: true
        key-store: classpath:spring_security.p12
        key-store-password: spring_security
        key-store-type: PKCS12
        key-alias: spring_security

spring:
    security:
        user:
            name: root
            password: rootroot
    datasource:
        url: jdbc:h2:tcp://localhost/~/workspace/web_practice/backend/spring_security/test
        driver-class-name: org.h2.Driver
        username: sa
    sql:
        init:
            mode: always
