drop table if exists user CASCADE;
drop table if exists role CASCADE;
drop table if exists permission CASCADE;
create table user
(
    id          bigint generated by default as identity,
    username    varchar(255),
    password    varchar(255),
    active      int,
    primary key(id)
);

create table role
(
    user_id     bigint,
    role        varchar(255),
    primary key (user_id, role),
    foreign key (user_id) references user 
    on update CASCADE
    on delete CASCADE
);

create table permission
(
    user_id     bigint,
    permission        varchar(255),
    primary key (user_id, permission),
    foreign key (user_id) references user 
    on update CASCADE
    on delete CASCADE
);

